package Entidades;
// Generated 29-may-2024 10:20:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private Integer idAlmacen;
     private String nombre;
     private String direccion;
     private Set inventarios = new HashSet(0);

    public Almacen() {
    }

	
    public Almacen(String nombre) {
        this.nombre = nombre;
    }
    public Almacen(String nombre, String direccion, Set inventarios) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.inventarios = inventarios;
    }
   
    public Integer getIdAlmacen() {
        return this.idAlmacen;
    }
    
    public void setIdAlmacen(Integer idAlmacen) {
        this.idAlmacen = idAlmacen;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }




}


