package Entidades;
// Generated 29-may-2024 10:20:15 by Hibernate Tools 4.3.1



/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private Integer idInventario;
     private Almacen almacen;
     private Producto producto;
     private int cantidadStock;

    public Inventario() {
    }

	
    public Inventario(int cantidadStock) {
        this.cantidadStock = cantidadStock;
    }
    public Inventario(Almacen almacen, Producto producto, int cantidadStock) {
       this.almacen = almacen;
       this.producto = producto;
       this.cantidadStock = cantidadStock;
    }
   
    public Integer getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(Integer idInventario) {
        this.idInventario = idInventario;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidadStock() {
        return this.cantidadStock;
    }
    
    public void setCantidadStock(int cantidadStock) {
        this.cantidadStock = cantidadStock;
    }




}


