package Entidades;
// Generated 29-may-2024 10:20:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer idPedido;
     private Cliente cliente;
     private Producto producto;
     private Vendedor vendedor;
     private int cantidad;
     private BigDecimal precioUnitario;
     private Date fechaPedido;
     private BigDecimal total;
     private String direccionEnvio;

    public Pedidos() {
    }

	
    public Pedidos(int cantidad, BigDecimal precioUnitario, Date fechaPedido) {
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
        this.fechaPedido = fechaPedido;
    }
    public Pedidos(Cliente cliente, Producto producto, Vendedor vendedor, int cantidad, BigDecimal precioUnitario, Date fechaPedido, BigDecimal total, String direccionEnvio) {
       this.cliente = cliente;
       this.producto = producto;
       this.vendedor = vendedor;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.fechaPedido = fechaPedido;
       this.total = total;
       this.direccionEnvio = direccionEnvio;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getDireccionEnvio() {
        return this.direccionEnvio;
    }
    
    public void setDireccionEnvio(String direccionEnvio) {
        this.direccionEnvio = direccionEnvio;
    }




}


