package Entidades;
// Generated 01-jun-2024 17:02:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int codigo;
     private Categoria categoria;
     private Proveedor proveedor;
     private String nombre;
     private int stock;
     private BigDecimal precioUnidad;
     private String modelo;
     private String marca;
     private String otros;
     private Inventario inventario;

    public Productos() {
    }

	
    public Productos(int codigo, String nombre, int stock, BigDecimal precioUnidad) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.stock = stock;
        this.precioUnidad = precioUnidad;
    }
    public Productos(int codigo, Categoria categoria, Proveedor proveedor, String nombre, int stock, BigDecimal precioUnidad, String modelo, String marca, String otros, Inventario inventario) {
       this.codigo = codigo;
       this.categoria = categoria;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.stock = stock;
       this.precioUnidad = precioUnidad;
       this.modelo = modelo;
       this.marca = marca;
       this.otros = otros;
       this.inventario = inventario;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public BigDecimal getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(BigDecimal precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getOtros() {
        return this.otros;
    }
    
    public void setOtros(String otros) {
        this.otros = otros;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }




}


