package Entidades;
// Generated 29-may-2024 10:20:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String contacto;
     private String telefono;
     private String email;
     private String nombreEmpresa;
     private Set productos = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String dni, String nombre) {
        this.dni = dni;
        this.nombre = nombre;
    }
    public Proveedor(String dni, String nombre, String contacto, String telefono, String email, String nombreEmpresa, Set productos) {
       this.dni = dni;
       this.nombre = nombre;
       this.contacto = contacto;
       this.telefono = telefono;
       this.email = email;
       this.nombreEmpresa = nombreEmpresa;
       this.productos = productos;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


