package Entidades;
// Generated 29-may-2024 10:20:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String telefono;
     private String email;
     private Set pedidoses = new HashSet(0);

    public Vendedor() {
    }

	
    public Vendedor(String dni, String nombre) {
        this.dni = dni;
        this.nombre = nombre;
    }
    public Vendedor(String dni, String nombre, String telefono, String email, Set pedidoses) {
       this.dni = dni;
       this.nombre = nombre;
       this.telefono = telefono;
       this.email = email;
       this.pedidoses = pedidoses;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


